# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Documents\程式作品\平板\DLsiteFilenameGetter\WindowDesign\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DLSiteGetWindow(object):
    def setupUi(self, DLSiteGetWindow):
        DLSiteGetWindow.setObjectName("DLSiteGetWindow")
        DLSiteGetWindow.resize(711, 505)
        font = QtGui.QFont()
        font.setPointSize(12)
        DLSiteGetWindow.setFont(font)
        self.lblInputNumber = QtWidgets.QLabel(DLSiteGetWindow)
        self.lblInputNumber.setGeometry(QtCore.QRect(30, 20, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblInputNumber.setFont(font)
        self.lblInputNumber.setObjectName("lblInputNumber")
        self.txtInputNumber = QtWidgets.QLineEdit(DLSiteGetWindow)
        self.txtInputNumber.setGeometry(QtCore.QRect(90, 20, 511, 20))
        self.txtInputNumber.setObjectName("txtInputNumber")
        self.tableParameters = QtWidgets.QTableWidget(DLSiteGetWindow)
        self.tableParameters.setGeometry(QtCore.QRect(20, 50, 671, 311))
        self.tableParameters.setObjectName("tableParameters")
        self.tableParameters.setColumnCount(2)
        self.tableParameters.setRowCount(11)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tableParameters.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tableParameters.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tableParameters.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tableParameters.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tableParameters.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tableParameters.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tableParameters.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tableParameters.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tableParameters.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tableParameters.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tableParameters.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tableParameters.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tableParameters.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableParameters.setItem(1, 0, item)
        self.lblOutput = QtWidgets.QLabel(DLSiteGetWindow)
        self.lblOutput.setGeometry(QtCore.QRect(30, 440, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblOutput.setFont(font)
        self.lblOutput.setObjectName("lblOutput")
        self.txtOutput = QtWidgets.QLineEdit(DLSiteGetWindow)
        self.txtOutput.setGeometry(QtCore.QRect(90, 440, 601, 20))
        self.txtOutput.setObjectName("txtOutput")
        self.btnGetData = QtWidgets.QPushButton(DLSiteGetWindow)
        self.btnGetData.setGeometry(QtCore.QRect(620, 20, 75, 23))
        self.btnGetData.setObjectName("btnGetData")
        self.lblReplaceFormat = QtWidgets.QLabel(DLSiteGetWindow)
        self.lblReplaceFormat.setGeometry(QtCore.QRect(30, 410, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblReplaceFormat.setFont(font)
        self.lblReplaceFormat.setObjectName("lblReplaceFormat")
        self.txtReplaceFormat = QtWidgets.QLineEdit(DLSiteGetWindow)
        self.txtReplaceFormat.setGeometry(QtCore.QRect(90, 410, 601, 20))
        self.txtReplaceFormat.setObjectName("txtReplaceFormat")
        self.btnDoReplace = QtWidgets.QPushButton(DLSiteGetWindow)
        self.btnDoReplace.setGeometry(QtCore.QRect(620, 470, 75, 23))
        self.btnDoReplace.setObjectName("btnDoReplace")
        self.comboPrefix = QtWidgets.QComboBox(DLSiteGetWindow)
        self.comboPrefix.setGeometry(QtCore.QRect(90, 380, 271, 22))
        self.comboPrefix.setEditable(True)
        self.comboPrefix.setObjectName("comboPrefix")
        self.lblPrefix = QtWidgets.QLabel(DLSiteGetWindow)
        self.lblPrefix.setGeometry(QtCore.QRect(30, 380, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblPrefix.setFont(font)
        self.lblPrefix.setObjectName("lblPrefix")
        self.lblPostfix = QtWidgets.QLabel(DLSiteGetWindow)
        self.lblPostfix.setGeometry(QtCore.QRect(370, 380, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblPostfix.setFont(font)
        self.lblPostfix.setObjectName("lblPostfix")
        self.comboPostfix = QtWidgets.QComboBox(DLSiteGetWindow)
        self.comboPostfix.setGeometry(QtCore.QRect(420, 380, 271, 22))
        self.comboPostfix.setEditable(True)
        self.comboPostfix.setObjectName("comboPostfix")

        self.retranslateUi(DLSiteGetWindow)
        QtCore.QMetaObject.connectSlotsByName(DLSiteGetWindow)

    def retranslateUi(self, DLSiteGetWindow):
        _translate = QtCore.QCoreApplication.translate
        DLSiteGetWindow.setWindowTitle(_translate("DLSiteGetWindow", "Dialog"))
        self.lblInputNumber.setText(_translate("DLSiteGetWindow", "編號："))
        item = self.tableParameters.verticalHeaderItem(0)
        item.setText(_translate("DLSiteGetWindow", "遊戲編號"))
        item = self.tableParameters.verticalHeaderItem(1)
        item.setText(_translate("DLSiteGetWindow", "遊戲名稱"))
        item = self.tableParameters.verticalHeaderItem(2)
        item.setText(_translate("DLSiteGetWindow", "下載數"))
        item = self.tableParameters.verticalHeaderItem(3)
        item.setText(_translate("DLSiteGetWindow", "社團名稱"))
        item = self.tableParameters.verticalHeaderItem(4)
        item.setText(_translate("DLSiteGetWindow", "社團網站"))
        item = self.tableParameters.verticalHeaderItem(5)
        item.setText(_translate("DLSiteGetWindow", "販售日期"))
        item = self.tableParameters.verticalHeaderItem(6)
        item.setText(_translate("DLSiteGetWindow", "系列名稱"))
        item = self.tableParameters.verticalHeaderItem(7)
        item.setText(_translate("DLSiteGetWindow", "年齡指定"))
        item = self.tableParameters.verticalHeaderItem(8)
        item.setText(_translate("DLSiteGetWindow", "作品形式"))
        item = self.tableParameters.verticalHeaderItem(9)
        item.setText(_translate("DLSiteGetWindow", "檔案形式"))
        item = self.tableParameters.verticalHeaderItem(10)
        item.setText(_translate("DLSiteGetWindow", "對應系統"))
        item = self.tableParameters.horizontalHeaderItem(0)
        item.setText(_translate("DLSiteGetWindow", "替換TAG"))
        item = self.tableParameters.horizontalHeaderItem(1)
        item.setText(_translate("DLSiteGetWindow", "內容"))
        __sortingEnabled = self.tableParameters.isSortingEnabled()
        self.tableParameters.setSortingEnabled(False)
        self.tableParameters.setSortingEnabled(__sortingEnabled)
        self.lblOutput.setText(_translate("DLSiteGetWindow", "檔名："))
        self.btnGetData.setText(_translate("DLSiteGetWindow", "GET"))
        self.lblReplaceFormat.setText(_translate("DLSiteGetWindow", "格式："))
        self.btnDoReplace.setText(_translate("DLSiteGetWindow", "GO"))
        self.lblPrefix.setText(_translate("DLSiteGetWindow", "前綴："))
        self.lblPostfix.setText(_translate("DLSiteGetWindow", "後綴："))

